-- ═══════════════════════════════════════════════════════════════════
-- HTTP API — SQLite Schema
--
-- Table dependency order:
--   projects
--   → environments → env_variables
--   → collections  → apis
--                    → api_params
--                    → api_responses → api_fields
--   api_executions (created first; example_id is a logical foreign key)
--   -> api_examples (source_execution_id points back to api_executions)
--
-- Notes:
--   api_executions.example_id and api_examples.source_execution_id form
--   a bidirectional association. SQLite does not support cyclic foreign keys,
--   so example_id remains a logical foreign key only.
--   BOOLEAN values are stored as INTEGER: 0 = false, 1 = true.
--   JSONB values are stored as TEXT and serialized by the application layer.
--   TEXT[] values are stored as JSON array strings such as '["tag1","tag2"]'.
--   All primary keys are generated by the application layer (UUID v4).
-- ═══════════════════════════════════════════════════════════════════

PRAGMA foreign_keys = ON;

-- ── projects ──────────────────────────────────────────────────────
-- Shared container for environments and collections; single-user setups usually have one project.
CREATE TABLE IF NOT EXISTS projects (
  id          TEXT     PRIMARY KEY,
  name        TEXT     NOT NULL,
  description TEXT,
  created_at  DATETIME NOT NULL DEFAULT (datetime('now')),
  updated_at  DATETIME NOT NULL DEFAULT (datetime('now'))
);

-- ── environments ──────────────────────────────────────────────────
-- Project-level environment config; base_url is shared by all collections.
CREATE TABLE IF NOT EXISTS environments (
  id          TEXT     PRIMARY KEY,
  project_id  TEXT     NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name        TEXT     NOT NULL,                    -- "Production" / "Staging" / "Dev"
  base_url    TEXT     NOT NULL DEFAULT '',         -- "https://api.example.com"
  env_type    TEXT     NOT NULL DEFAULT 'dev'
                CHECK (env_type IN ('production', 'staging', 'dev')),
  sort_order  INTEGER  NOT NULL DEFAULT 0,
  created_at  DATETIME NOT NULL DEFAULT (datetime('now')),
  updated_at  DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_environments_project ON environments (project_id);

-- ── env_variables ─────────────────────────────────────────────────
-- Environment variables; when is_secret=1, value stores AES-256-GCM ciphertext and the UI masks it.
CREATE TABLE IF NOT EXISTS env_variables (
  id             TEXT     PRIMARY KEY,
  environment_id TEXT     NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
  key            TEXT     NOT NULL,
  value          TEXT     NOT NULL DEFAULT '',
  is_secret      INTEGER  NOT NULL DEFAULT 0,
  created_at     DATETIME NOT NULL DEFAULT (datetime('now')),
  updated_at     DATETIME NOT NULL DEFAULT (datetime('now')),
  UNIQUE (environment_id, key)
);

CREATE INDEX IF NOT EXISTS idx_env_variables_env ON env_variables (environment_id);

-- ── collections ───────────────────────────────────────────────────
-- API collections, typically corresponding to a controller/router group in the sidebar tree.
CREATE TABLE IF NOT EXISTS collections (
  id          TEXT     PRIMARY KEY,
  project_id  TEXT     NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name        TEXT     NOT NULL,
  description TEXT,
  sort_order  INTEGER  NOT NULL DEFAULT 0,
  created_by  TEXT,
  created_at  DATETIME NOT NULL DEFAULT (datetime('now')),
  updated_at  DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_collections_project ON collections (project_id);

-- ── apis ──────────────────────────────────────────────────────────
-- Individual API definitions used by both the UI documentation view and MCP capability metadata.
-- MCP fields (intent / risk / need_confirmation / side_effect / retry_strategy / context / metadata)
-- are written by capability schema pushes and are not overwritten by the UI.
CREATE TABLE IF NOT EXISTS apis (
  id                TEXT     PRIMARY KEY,
  collection_id     TEXT     NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
  name              TEXT     NOT NULL,
  method            TEXT     NOT NULL
                      CHECK (method IN ('GET','POST','PUT','DELETE','PATCH','HEAD','OPTIONS')),
  path              TEXT     NOT NULL,              -- "/api/v1/users/:id"
  description       TEXT,
  request_body_type TEXT     NOT NULL DEFAULT 'json'
                      CHECK (request_body_type IN ('json', 'form', 'multipart', 'none')),

  -- MCP capability fields
  intent            TEXT     NOT NULL DEFAULT '[]', -- JSON array: ["Create order","Place order"]
  risk              TEXT     NOT NULL DEFAULT 'LOW'
                      CHECK (risk IN ('LOW', 'MEDIUM', 'HIGH')),
  need_confirmation INTEGER  NOT NULL DEFAULT 0,    -- whether a call requires confirmation
  side_effect       INTEGER  NOT NULL DEFAULT 0,    -- whether the call has side effects
  retry_strategy    TEXT     NOT NULL DEFAULT 'default'
                      CHECK (retry_strategy IN ('default', 'disabled', 'idempotent')),
  context           TEXT     NOT NULL DEFAULT '[]', -- JSON array: ["user_id","order_id"]
  metadata          TEXT,                           -- JSON object for framework extensions

  created_by        TEXT,
  created_at        DATETIME NOT NULL DEFAULT (datetime('now')),
  updated_at        DATETIME NOT NULL DEFAULT (datetime('now')),
  UNIQUE (collection_id, method, path)
);

CREATE INDEX IF NOT EXISTS idx_apis_collection ON apis (collection_id);
CREATE INDEX IF NOT EXISTS idx_apis_risk       ON apis (risk);

-- ── api_params ────────────────────────────────────────────────────
-- Query, path, header, and cookie parameters are always flat.
-- Request body fields are stored in api_fields when response_id IS NULL.
CREATE TABLE IF NOT EXISTS api_params (
  id          TEXT     PRIMARY KEY,
  api_id      TEXT     NOT NULL REFERENCES apis(id) ON DELETE CASCADE,
  location    TEXT     NOT NULL DEFAULT 'query'
                CHECK (location IN ('query', 'path', 'header', 'cookie')),
  name        TEXT     NOT NULL,
  type        TEXT     NOT NULL DEFAULT 'string'
                CHECK (type IN ('string', 'integer', 'number', 'boolean')),
  required    INTEGER  NOT NULL DEFAULT 0,
  description TEXT,
  example     TEXT,
  sort_order  INTEGER  NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_api_params_api ON api_params (api_id);

-- ── api_responses ─────────────────────────────────────────────────
-- Supported response codes; response body fields live in api_fields when response_id IS NOT NULL.
CREATE TABLE IF NOT EXISTS api_responses (
  id           TEXT     PRIMARY KEY,
  api_id       TEXT     NOT NULL REFERENCES apis(id) ON DELETE CASCADE,
  status_code  INTEGER  NOT NULL,                  -- 200 / 400 / 401 / 404 ...
  description  TEXT,                               -- "Created" / "Validation failed"
  content_type TEXT     NOT NULL DEFAULT 'application/json',
  sort_order   INTEGER  NOT NULL DEFAULT 0,
  UNIQUE (api_id, status_code)
);

CREATE INDEX IF NOT EXISTS idx_api_responses_api ON api_responses (api_id);

-- ── api_fields ────────────────────────────────────────────────────
-- Request body and response body field definitions with recursive nesting support.
--
--   response_id IS NULL  -> request body field (interpreted via apis.request_body_type)
--   response_id NOT NULL -> response body field for that status code
--   parent_id   IS NULL  -> root node for the current scope
--   name        IS NULL  -> unnamed array item node
CREATE TABLE IF NOT EXISTS api_fields (
  id          TEXT     PRIMARY KEY,
  api_id      TEXT     NOT NULL REFERENCES apis(id) ON DELETE CASCADE,
  response_id TEXT     REFERENCES api_responses(id) ON DELETE CASCADE,
  parent_id   TEXT     REFERENCES api_fields(id) ON DELETE CASCADE,
  name        TEXT,
  type        TEXT     NOT NULL DEFAULT 'string'
                CHECK (type IN ('string', 'integer', 'number', 'boolean', 'object', 'array')),
  format      TEXT,                                -- "int64" / "date-time" / "uuid" / "email"
  required    INTEGER  NOT NULL DEFAULT 0,
  description TEXT,
  example     TEXT,
  enum_values TEXT,                                -- JSON array: ["admin","user","guest"]
  constraints TEXT,                                -- JSON object: {"minimum":1,"maxLength":100,"pattern":"^[a-z]+"}
  sort_order  INTEGER  NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_api_fields_api      ON api_fields (api_id);
CREATE INDEX IF NOT EXISTS idx_api_fields_response ON api_fields (response_id);
CREATE INDEX IF NOT EXISTS idx_api_fields_parent   ON api_fields (parent_id);

-- ── api_executions ────────────────────────────────────────────────
-- Every actual HTTP request, whether triggered manually or by AI.
-- Created before api_examples to avoid a cyclic dependency.
-- example_id is a logical foreign key maintained by the application layer.
CREATE TABLE IF NOT EXISTS api_executions (
  id              TEXT     PRIMARY KEY,
  api_id          TEXT     REFERENCES apis(id) ON DELETE SET NULL,
  environment_id  TEXT     REFERENCES environments(id) ON DELETE SET NULL,
  example_id      TEXT,                            -- logical foreign key -> api_examples.id
  session_id      TEXT,                            -- logical foreign key -> sessions.id (core schema)
  step_id         TEXT,                            -- logical foreign key -> steps.id (core schema)
  triggered_by    TEXT     NOT NULL DEFAULT 'manual'
                    CHECK (triggered_by IN ('manual', 'ai')),

  -- Actual outgoing request after variable substitution; safe to replay.
  req_method      TEXT     NOT NULL,
  req_url         TEXT     NOT NULL,
  req_headers     TEXT,                            -- JSON object
  req_body        TEXT,

  -- Actual received response
  res_status      INTEGER,
  res_headers     TEXT,                            -- JSON object
  res_body        TEXT,
  res_duration_ms INTEGER,
  res_error       TEXT,                            -- network-layer errors such as timeout or DNS failure

  created_at      DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_executions_api     ON api_executions (api_id);
CREATE INDEX IF NOT EXISTS idx_executions_session ON api_executions (session_id);
CREATE INDEX IF NOT EXISTS idx_executions_example ON api_executions (example_id);
CREATE INDEX IF NOT EXISTS idx_executions_time    ON api_executions (created_at DESC);

-- ── api_examples ──────────────────────────────────────────────────
-- Reusable request examples created manually or saved from execution history.
-- When is_default=1, the example is shown as the primary example in API docs.
-- query_params and headers use arrays to support duplicate keys and enabled state:
--   [{"key": "page", "value": "1", "enabled": true}]
CREATE TABLE IF NOT EXISTS api_examples (
  id                  TEXT     PRIMARY KEY,
  api_id              TEXT     NOT NULL REFERENCES apis(id) ON DELETE CASCADE,
  environment_id      TEXT     REFERENCES environments(id) ON DELETE SET NULL,
  name                TEXT     NOT NULL,           -- "Successful login" / "Missing token - 401"
  description         TEXT,
  is_default          INTEGER  NOT NULL DEFAULT 0,

  -- Request parameter values
  path_params         TEXT,                        -- JSON object: {"user_id": "42"}
  query_params        TEXT,                        -- JSON array:  [{"key","value","enabled"}]
  headers             TEXT,                        -- JSON array:  [{"key","value","enabled"}]
  body                TEXT,

  -- Response snapshot used for documentation
  res_status          INTEGER,
  res_headers         TEXT,                        -- JSON object
  res_body            TEXT,

  -- Source execution used to save this example
  source_execution_id TEXT     REFERENCES api_executions(id) ON DELETE SET NULL,

  sort_order          INTEGER  NOT NULL DEFAULT 0,
  created_by          TEXT,
  created_at          DATETIME NOT NULL DEFAULT (datetime('now')),
  updated_at          DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_api_examples_api ON api_examples (api_id);
